environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
      ARCH: "64"
      NUMPY_VERSION: "1.15.*"
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml

  # Install dependencies
  - activate devel
 
  # Add to path the current folder
  - "SET PYTHONPATH=%PYTHONPATH%;%CD%"

  # Install SHARPpy
  - python setup.py -q install

  # Resize the screen 
  #- nuget restore
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))  
  - ps: Set-ScreenResolution 1366 768

build: off

# Turning off Test Script for now  
test_script:
#  - sharppy examples/data/14061619.OAX
  - pytest -v

after_test:
  - "conda list"
  - "cd runsharp"
  - "pyinstaller SHARPpy-win7-%ARCH%.spec"
  - "cd .."
#  - "move dist\\SHARPpy.exe dist\\SHARPpy%ARCH%.exe"

artifacts:
  - path: "runsharp\\dist\\SHARPpy64.exe"
    name: binary
 
  - path: "*.png"
    name: test images

  - path: "examples\\data\\14061619.png"
    name: test gui

deploy:
  provider: GitHub
  release: $(appveyor_repo_tag_name)
  auth_token:
    secure: DB6sQwYCM7Dhhy+mjPkMd6kclvw0Sc2wglTJxcTBQue63dtIQRNa1dz/aqJG7Ygc
  artifact: "runsharp\\dist\\SHARPpy64.exe"
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true

# Don't deploy because andover-off 
