env:
  global:
    - PYTHON_VERSION
    - DISPLAY_AVAIL
    - BUILD_CONDA
    - BUILD_DOCS
    - BUILD_BINARY
    - MPL_VERSION=2.2.3
matrix:
  include:
  - os: linux
    language: generic
    env: 
      - PYTHON_VERSION="3.6" BUILD_CONDA="YES" NUMPY_VERSION=1.15.*
  - os: osx
    language: generic
    env: 
      - PYTHON_VERSION="3.6" DISPLAY_AVAIL="NO" BUILD_BINARY="YES" NUMPY_VERSION=1.15.*
  - os: linux
    language: generic
    env:
      - PYTHON_VERSION="2.7" NUMPY_VERSION=1.15.*
  - os: linux
    language: generic
    env:
      - PYTHON_VERSION="3.6" BUILD_DOCS="YES" NUMPY_VERSION=1.15.* COVERALLS="YES"
before_install:
- source ci/install.sh
install:
- pip install -e .
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run pytest -v --cov ; else pytest -v --cov ; fi
# If the test script passes, deploy if it's tagged..generate the binaries.
after_success:
# Deploy test information to coveralls
- if [[ "$COVERALLS" == "YES" ]] ; then coveralls || echo "Coveralls upload failed" ;fi
# Build the binary if it's a new tag.
- if [[ -n "$TRAVIS_TAG" ]]; then source ci/make_binary.sh; fi
before_deploy:
- cd dist
- if [ "$BUILD_BINARY" == "YES" ] && [ -n "$TRAVIS_TAG" ]; then zip -r SHARPpy-osx.zip SHARPpy.app; fi
- cd ..
# Ship the binaries to Github and PyPI and conda
deploy:
# Deploy the binaries to Github Releases
 - provider: releases
   api_key:
     secure: upm1CAgyi6Qv+KaHAo/v3mDyaXYSFs+vm0qS1D7IUDapGIhOTfqDgOpS71bFAnM9w+FRc7S3foxmymsHZsK97LVOEqHNibBtSmELVzhv2VHoCfAUnHaOzCi/z4DHx3QKn2ALLymFfG4O7XzSC7urHue9/h9DWy51srokafP3QOnI6sWHkWGOOOv0i13MDzv2RxMza7+PT69bQ2vFk2ujwAthanDySeXyf2kJ7WYj1cuEBfASBs+diVUSqk7FxJO7OQhyLCCn5bSS3Otvg9tkHL8H7WU6JoGHLBoUPDUxCl0KePgie6hZvaJFAlhcJfmSA4NsTQfunFnbHa2rPFPUTLO6RgEbtD0Th85VORmmEeJ8O+GmvZIRBZUiMxPAbb1DXPwI6XtgoFhNiV5rkut4JtL3BgRmAfIdAsvBfNbozgRpHAOpoiIzx/8wan+o73h6K1y+qfQwxBw+cJAL3n0A2M3x7/mpALLf3JLD8E5KKLbp/kedPIF2vKXZ92h85H9AkMopHqLHQGj86M0qHbQyMp6OHR2ivG2K9qqtzAaUNglQrUaQOHeaBZ8ZT7+mhpdhaN1w5fmuYPRchVzyNbM3DtdiUfAGc6adZPUaUktbiIpLigjwS6BO4FALngrI9+M+kk8qHv/zukOiGawzueCDUGc79G/8LI7Q1EKkiqyI+3E=
   file_glob: true
   file: dist/SHARPpy*.zip
   skip_cleanup: true
   on:
     repo: sharppy/SHARPpy
     tags: true
     branch: andover
# Deploy the code to PyPI
 - provider: pypi
   user: sharppy
   password:
     secure: "qgE7Hef6m9m6xf0CU976z/7KbpSaRIeucwVztsJQQCqP97FMnkb0bL0fhQMoxkVti1VCAuF9FXvWzWBKuKeu+sqP3pEE7GYlTVqq4kN3W55DleVFbyWy3Fyhu+6pRJL168kZg1rCNboX7Xw8RwI0l0r3DiSvjqWSYvOfdabgYlECImS4XjxRYxN2GTDXG3D37soWiBbi7rqDj33fitUHXyJMLdPhtbGs85BStG9Op2aRXibtCH2Lo/EtY7PkWaxY8F5aXrKiufHPvkpow8S2XKD1VdWpHAV+5lO7ai9N8Z9zyogYLzIAfPqHDx6afQWUknRBn8Ot7k4Kt3cBGEhdvtAH8jhZGCmqDPsk1+qgx/OyWK9iiJsvsJWKmTf286AZl5vxO9NH1fZL0LpYQ5XvwrVi83eygLttEOU0I6ggngflJfs5KvfZXmvODdfK4oVzn3mJODbncLoYz1KxNZRPUFWycmkDaPmy2YyPjRnqE1S6SOP1zGVAEO2Leq/lGbB0J18b103oehyp6+t9KnpsoEhPDsr68xKCkKLl5QXVlfGikHJAMVI/CM0Hh8bva6bTNP5Ulsko6vYyvfGlbI0rEW3OJikvh0051M0lS175j3LMGj5Bs1iFZX43KoyebcfqYDtRQdrvigzsRAZoR9BdBAnVZtO5mfFMkrUtIX94Au8="
   distributions: sdist bdist_wheel
   upload_docs: no
   on:
     repo: sharppy/SHARPpy
     tags: true
     branch: andover
     condition: "$BUILD_CONDA = YES"
# Deploy code to conda
 - provider: script
   script: bash ci/deploy_conda.sh
   on:
     repo: sharppy/SHARPpy
     tags: true
     branch: andover
     condition: "$BUILD_CONDA = YES"
# Deploy docs to Github Pages
 - provider: script
   script: bash ci/build_docs.sh
   on:
     repo: sharppy/SHARPpy
     tags: true
     branch: andover
     condition: "$BUILD_DOCS = YES"
