name: devel
channels:
  - conda-forge
  - conda-forge/label/testing
  - anaconda
dependencies:
  - python=3
  - numpy=1.15.*
  - pyside2
  - sphinx
  - pytest
  - qtpy
  - sphinx-gallery
  - sphinx_rtd_theme
  - requests
  - python-dateutil 
  - pyinstaller
  - setuptools
  - pip
  - pip:
    - sphinx-prompt
    - pydocstyle
